name: Build test
on:
  push:
    tags:
  pull_request:
    branches:
      - master
env:
  MASTER_BRANCH: refs/heads/master
  INDEX_BUILDER_COMMIT: 4150e12d68a53151a302c9a6cb84f738c711a9f2
jobs:
  universal-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.12
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip==24.2
        pip install -U setuptools==75.2.0 wheel
        ./rospy-builder/install.sh
        pip install rospy-builder/
    - name: Export branch suffix and make an empty directory
      if: github.ref == env.MASTER_BRANCH
      run: |
        echo BRANCH_SUFFIX=_pre >> $GITHUB_ENV
        mkdir -p any
      shell: bash
    - name: Download deployed packages
      if: github.ref != env.MASTER_BRANCH
      run: |
        git clone -b any https://github.com/Woz4tetra/rospy-simple.git any
        rm any/.git -rf
    - name: Build platform independent packages
      run: |
        rospy-build build -d any
    - name: Runs only when tagged or pushed to master
      if: startsWith(github.ref, 'refs/tags/') || github.ref == env.MASTER_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd any
        git init
        git config user.name "Woz4tetra"
        git config user.email "woz4tetra@gmail.com"
        git remote add origin https://woz4tetra:${GITHUB_TOKEN}@github.com/Woz4tetra/rospy-simple.git
        git checkout -b any${BRANCH_SUFFIX}
        touch .keep
        git add .
        git commit -am "Release $(date)"
        git push -f origin any${BRANCH_SUFFIX}

  native-build:
    needs: universal-build
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-22.04]
        python-version: ['3.11.12', '3.12.10']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages(Ubuntu)
      if: startsWith(matrix.platform, 'ubuntu-')
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        sudo apt-get update
        sudo apt install liblz4-dev sip-dev libeigen3-dev sip-dev libboost-all-dev
        echo BRANCH_NAME=Linux_${PYTHON_VERSION} >> $GITHUB_ENV
    - name: Install rospy-build
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools==75.2.0 wheel
        bash ./rospy-builder/install.sh
        pip install rospy-builder/
    - name: Export branch suffix and make an empty directory
      if: github.ref == env.MASTER_BRANCH
      run: |
        echo BRANCH_SUFFIX=_pre >> $GITHUB_ENV
        mkdir -p ${BRANCH_NAME}
      shell: bash
    - name: Download deployed packages
      if: github.ref != env.MASTER_BRANCH
      run: |
        git clone -b ${BRANCH_NAME} https://github.com/Woz4tetra/rospy-simple.git ${BRANCH_NAME} || true
        mkdir -p ${BRANCH_NAME}
        rm -rf ${BRANCH_NAME}/.git
      shell: bash
    - name: Build packages
      run: |
        rospy-build build -d ${BRANCH_NAME} --native
      shell: bash
    - name: Runs only when tagged or pushed to master
      if: startsWith(github.ref, 'refs/tags/') || github.ref == env.MASTER_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${BRANCH_NAME}
        git init
        git config user.name "Woz4tetra"
        git config user.email "woz4tetra@gmail.com"
        git remote add origin https://woz4tetra:${GITHUB_TOKEN}@github.com/Woz4tetra/rospy-simple.git
        git checkout -b ${BRANCH_NAME}${BRANCH_SUFFIX}
        touch .keep
        git add .
        git commit -am "Release $(date)"
        git push -f origin ${BRANCH_NAME}${BRANCH_SUFFIX}
      shell: bash

  update-pages:
    needs: native-build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.12
    - name: Prepare build env
      run: |
          python3 -m pip install --upgrade pip
          pip3 install git+https://github.com/rospypi/index_builder.git@${{ env.INDEX_BUILDER_COMMIT }}
    - name: Build index html
      run: |
          git clone https://github.com/Woz4tetra/rospy-simple.git simple
          mkdir index
          python3 -m index_builder repo --path simple index
          python3 -m index_builder repo --prefix pre --path simple index/_pre
    - name: Runs only when tagged or pushed to master
      if: startsWith(github.ref, 'refs/tags/') || github.ref == env.MASTER_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd index
        git init
        git config user.name "Woz4tetra"
        git config user.email "woz4tetra@gmail.com"
        git remote add origin https://woz4tetra:${GITHUB_TOKEN}@github.com/Woz4tetra/rospy-simple.git
        git checkout -b gh-pages
        touch .nojekyll
        git add .
        git commit -am "Release $(date)"
        git push -f origin gh-pages
      shell: bash
